### ISSUE TITLE
Montar o Backlog do Software RISO.

### ISSUE THREAD

**Issue by DanielRogs** [mdsreq-fga-unb/2024.1-RISO-#11]
### Task a ser executada.

Deverá ser montada na plataforma [JIRA](https://unbprojects.atlassian.net/jira/software/projects/RISO/boards/2?assignee=unassigned), cujo organiza os backlogs em épicos os ordena em um quadro Kanban. O backlog deverá ser montado baseado nos resultados da Issue #10, estabelecendo as User Stories e categorizando-os em épicos.

### Quais são as Definition´s of Done (DoD) da atividade?

- [ ] O Backlog do software foi documentado no Jira;
- [ ] As funcionalidades estão categorizadas em épicos;
- [ ] As funcionalidades possuem Histórias de Usuário.

**Comment by DanielRogs** [comment]
Atividade Concluída.
