### ISSUE TITLE
Backlog do Produto

### ISSUE THREAD

**Issue by phmelosilva** [mdsreq-fga-unb/2024.1-RISO-#54]
### Task a ser executada.

- [ ] O Backlog poderia estar em uma seção dedicada a ele, para que as atualizações sobre o mesmo sejam mais fáceis de se rastrear, levando em conta a importância desse artefato para o desenvolvimento do produto.
- [ ] Faltou indicar o nível de priorização de desenvolvimento das US e não há o uso de nenhuma técnica ou framework para isso. Um exemplo é a utilização da técnica MoSCoW para a definição de MVPs, o que é utilizada para a priorização das US e, consequentemente, dos requisitos.

### Quais são as Definition´s of Done (DoD) da atividade?

- [ ] Correção e aprimoramento do artefato em relação ao que foi indicado na descrição;

**Comment by DanielRogs** [comment]
Atividade concluída no último PR
